### ISSUE TITLE
Root package of generated source files moved to project root

### ISSUE THREAD

**Issue by jlchoike** [uPhyca/gradle-android-aspectj-plugin#9]
After adding your plugin to my project, I noticed that the generated source files located in build/generated/source/apt was copied to the project root. Before adding your plugin, my root package of the generated source (com) was only present in the generated source directory, but now I am find it in the project root.

FYI - I noticed the same behavior with the Maven AspectJ plugin. Is this something specific to the compiler, or is it a plugin issue? Please let me know what compiler options I have missed that lead to this behavior. Thanks!

**Comment by jlchoike-DL** [comment]
@esmasui are you familiar with why ajc copies source files to the build working directory?

**Comment by esmasui** [comment]
@jlchoike-DL I have never seen the problem. please send me the entire project to represent the issue?

**Comment by jlchoike-DL** [comment]
Disregard, I think this issue is not related to your plugin, and has to do
with the fact that Dagger source is generated in a non-standard location.
AJC is copying the code to the build's working directory.

On Fri, Feb 13, 2015 at 12:20 AM, Sosuke Masui <notifications@github.com>
wrote:

> @jlchoike-DL <https://github.com/jlchoike-DL> I have never seen the
> problem. please send me the entire project to represent the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uPhyca/gradle-android-aspectj-plugin/issues/9#issuecomment-74206797>
> .
>



-- 
Jan Choike

Application Development - Detroit Labs

1.248.629.0862

jan.choike@detroitlabs.com


More: http://detroitlabs.com
Blog: http://detroitlabs.com/blog
Twitter: http://twitter.com/detroitlabs
Facebook: http://facebook.com/detroitlabs

**Comment by tapasyakore** [comment]
@jlchoike-DL  how did you solve this ?

**Comment by esmasui** [comment]
@tapasyakore please try latest version, 0.9.13

**Comment by esmasui** [comment]
Doesn't reproduce the latest version of the plugin.
